"""updated documents table to include chunk to help ID in pinecone

Revision ID: b1183ff01ff1
Revises: b3667ca7c073
Create Date: 2024-12-28 18:08:37.722714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1183ff01ff1'
down_revision: Union[str, None] = 'b3667ca7c073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunk', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'chunk')
    # ### end Alembic commands ###
